title: Max Voitko
author: Max Voitko
email: max.voitko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Max Voitko blog about his life

# social links
twitter_username: mvoitko # DO NOT include the @ character, or else the build will fail!
github_username:  mvoitko # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
